linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - path: examples/
      linters:
        - gosec
        - gochecknoglobals
    - path: _test\.go
      linters:
        - errcheck
        - paralleltest
        - gochecknoglobals

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/go-chi/chi/v5
          - github.com/evgenymarkov/oasis
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/go-chi/chi/v5
          - github.com/stretchr/testify
          - github.com/evgenymarkov/oasis
