name: Check changes

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go get .

      # - name: Lint code
      #   uses: golangci/golangci-lint-action@v4
      #   with:
      #     version: v1.54

      - name: Run tests
        env:
          CGO_ENABLED: 0
        run: go test -v -race -shuffle on ./...
