name: Check changes

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Lint code
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
